// ── Snapshot Action Plan — Static Rule Tables ─────────────────
//
// All pushback items and question triggers are deterministic.
// They are selected/filtered based on the SnapshotSummary shape,
// not generated by an LLM.

import type { SnapshotSummary } from "../snapshot-summary";
import type { SnapshotPushbackItem } from "./types";

// ─── Pushback rule table ──────────────────────────────────────
//
// All six items are included; none are conditional.
// Order reflects how frequently each objection appears in practice.

export const PUSHBACK_RULES: SnapshotPushbackItem[] = [
  {
    pushback: "We have strong Glassdoor reviews — why does this matter?",
    counter:
      "Glassdoor is a destination platform: candidates arrive there after they already have you in mind. What this data shows is what happens one step earlier — when a candidate asks an AI assistant to name companies they should consider. If you are not in those results, you never get the Glassdoor visit. Strong employer brand on destination platforms does not translate to presence in AI-generated discovery responses, and that is the gap this assessment surfaces.",
  },
  {
    pushback: "AI search isn't mainstream for job seekers yet.",
    counter:
      "ChatGPT surpassed 400 million weekly active users in early 2025, and search behavior is shifting fastest among the exact candidates you are competing for: technical, analytical, early-career. The companies getting cited in AI responses today are building durable authority that compounds. Waiting until AI search is mainstream means catching up from behind against competitors who started now.",
  },
  {
    pushback: "Our recruiting team already handles employer brand.",
    counter:
      "Recruiting teams handle the funnel once candidates are already aware of you. What this assessment looks at is the upstream layer — the AI-generated responses that shape which companies a candidate considers before they ever reach a job board or careers page. That upstream layer is owned by content strategy and PR, not sourcing, and most recruiting teams do not have visibility into it yet.",
  },
  {
    pushback: "Can't we just improve our SEO instead?",
    counter:
      "Traditional SEO optimizes for clicks to your site. AI visibility optimizes for whether your company appears in AI-generated responses that candidates read without clicking anywhere. These are different signals — AI models weight citation authority, third-party mentions, and structured employer content rather than keyword density or backlink volume. The platforms that matter for AI citation (Glassdoor, Levels.fyi, Blind) are not ones you can rank on with standard SEO.",
  },
  {
    pushback: "We don't have budget for a full assessment right now.",
    counter:
      "The full assessment is designed to give you a complete picture — which specific queries you are losing, on which platforms, and exactly what content would close each gap. The Snapshot already shows the shape of the problem; the full assessment tells you precisely what to fix. Given the timelines for content and platform authority to compound, the cost of waiting tends to exceed the cost of the assessment by the time competitive gaps are visible in offer acceptance rates.",
  },
  {
    pushback: "We already work with a PR firm / employer brand agency.",
    counter:
      "Most employer brand agencies optimize for reach and sentiment on platforms they already know — LinkedIn, Glassdoor, Indeed. What they typically are not measuring is whether your company appears when an AI model synthesizes a response about who to work for in your category. That is a newer signal that most agencies are not yet tracking. This assessment gives you the data to brief your existing partners on where the specific gaps are, so their work is aimed at the right targets.",
  },
];

// ─── Question trigger logic ───────────────────────────────────
//
// Returns exactly 3 questions rule-based on the Snapshot shape.
// Priority: citation gap → competitor contrast → discovery → fallback.

export function selectQuestionsToAsk(summary: SnapshotSummary): string[] {
  const questions: string[] = [];

  // Citation gap question
  const citationGap = summary.citationGap.gapPlatforms.length;
  if (citationGap > 0) {
    const platforms = summary.citationGap.gapPlatforms.slice(0, 2).join(" and ");
    questions.push(
      `What is your current budget for managing presence on platforms like ${platforms || "Glassdoor and Levels.fyi"} — and who owns that work internally?`,
    );
  } else {
    questions.push(
      "What is your current budget for employer brand platforms outside of LinkedIn and Glassdoor, and who owns that strategy internally?",
    );
  }

  // Competitor contrast question
  const worstCompetitor = summary.competitorContrast.competitorSummaries
    .sort((a, b) => b.favorRate - a.favorRate)
    .at(0);
  if (worstCompetitor && worstCompetitor.favorRate > 0.5) {
    questions.push(
      `When you think about candidates who are weighing you against ${worstCompetitor.competitorName}, what do you believe is the main reason they choose ${worstCompetitor.competitorName} over you?`,
    );
  } else {
    questions.push(
      "When candidates choose a competitor over you, what reason do they typically give — and how are you currently measuring that?",
    );
  }

  // Discovery gap question
  const discoveryMentionRate = summary.discoveryMentionRate;
  if (discoveryMentionRate < 0.2) {
    questions.push(
      "If a strong candidate asked an AI assistant to list the top companies to work for in your space, would you expect your company to appear — and have you tested that recently?",
    );
  } else {
    questions.push(
      "How are you currently tracking where your employer brand appears in candidate research, outside of platform-specific analytics from Glassdoor or LinkedIn?",
    );
  }

  return questions.slice(0, 3);
}
